######################################
## Configuration file for oidc-proxy##
######################################
#                                   ##
# There are four sections:          ##
# 1. openid_providers               ##
# 2. proxy                          ##
# 3. services                       ##
# 4. access control
######################################


# OpenId- Providers:
# You need to fill at least one provider
# The keys can be arbitrary
#openid_providers:
#    default:
#        configuration_url: https://openid-provider.example.com/auth/realms/master/
#        configuration_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmYTM2N2E0MS0yNDRjLTQwNGUtYjU3NS05MDhhNDM2ZTc2YTMifQ.eyJqdGkiOiJiOWE1ZDUxNC04NDc4LTQ0NzktYmE2OS0wMGM0YjYzYzc4MWEiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTc2MjI4NDgyLCJpc3MiOiJodHRwczovL29wZW5pZC1wcm92aWRlci5leGFtcGxlLmNvbS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJodHRwczovL29wZW5pZC1wcm92aWRlci5leGFtcGxlLmNvbS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJ0eXAiOiJJbml0aWFsQWNjZXNzVG9rZW4ifQ.JIxOTxkOjhR0NIDqKYiN5EvdNk1Xtg8vDdV7LVjd0J8
#    second:
#        configuration_url: https://openid-provider2.example.com/auth/realms/master/
#        configuration_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5MDEzZDRkNS1jYTEwLTQyODItYmRjMy1jNWU5ZGQ3NDI4MWIifQ.eyJqdGkiOiJjNWI5YmY0Zi03ZDI4LTRhNDEtODc5OC04N2Q0M2QzYTlhMDAiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTc2MjI4NTE0LCJpc3MiOiJodHRwczovL29wZW5pZC1wcm92aWRlcjIuZXhhbXBsZS5jb20vYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiaHR0cHM6Ly9vcGVuaWQtcHJvdmlkZXIyLmV4YW1wbGUuY29tL2F1dGgvcmVhbG1zL21hc3RlciIsInR5cCI6IkluaXRpYWxBY2Nlc3NUb2tlbiJ9.NWDGljUARkwBl0oLC62H_U7L_4TsXvsVx_TubxpNILk
#

# Proxy:
# You don't need to change supply the values that are *NOT* commented out!
proxy:
    address: 0.0.0.0
    port: 443
#    keyfile: /etc/ssl/private/python-proxy.example.com.key
#    certfile: /etc/ssl/private/python-proxy.example.com.crt
#    domainname: https://python-proxy.example.com/
    username: www-data
    groupname: www-data
    secrets: /var/lib/oidc-proxy/secrets.yml
    redirect: /secure/redirect_uris
#    redirect_uris:
#        - https://python-proxy.example.com/secure/redirect_uris
#    contacts:
#        - info@konstantinzangerle.de

# Services:
# You need to supply at least one provider
#services:
#    serviceA:
#        origin_URL: http://service-a.example.com
#        proxy_URL: /serviceA
#        AC: com.example.policysets.loggedIn
#    serviceB:
#        origin_URL: http://service-a.example.com
#        proxy_URL: /serviceB
#        AC: com.example.policysets.alwaysDeny
#    serviceC:
#        origin_URL: http://service-a.example.com
#        proxy_URL: /serviceC
#        AC: com.example.policysets.inTestGroup



#access_control:
#    json_dir:
#       - /etc/oidc-proxy/acl

