#Test
openid_providers:
    default:
        human_readable_name: Keycloak Test Instance 1
        configuration_url: https://openid-provider.example.com/auth/realms/master/
        configuration_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1ZGYxY2VkMi1jMWY2LTQ5ZmQtYWUxYy00ZDU0MmQ0MWZmNzgifQ.eyJqdGkiOiIyZDM4Y2UxZC1kNWI5LTQxOWUtYjk0Zi1lNTU0NjM4MTAxMWMiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTgyMjA5MDcyLCJpc3MiOiJodHRwczovL29wZW5pZC1wcm92aWRlci5leGFtcGxlLmNvbS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJodHRwczovL29wZW5pZC1wcm92aWRlci5leGFtcGxlLmNvbS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJ0eXAiOiJJbml0aWFsQWNjZXNzVG9rZW4ifQ.MaCbmnpR7WDL86Z0wvTmDxqRFYvnGGHSymtkrl72tEg
        special_claim2scope:
            age:
                - age
        redirect_paths:
            - secure/keycloak
    second:
        human_readable_name: Keycloak Test Instance 2
        configuration_url: https://openid-provider2.example.com/auth/realms/master/
        configuration_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlZDBjNWY2MS0wNjM5LTRiMDQtOTVjZS1hMzhjNGJlMzczZWIifQ.eyJqdGkiOiI1OWYyZGY4My1mYjQ4LTRiZGYtYTc3NC02ODI5NTJjZDEwYTkiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTc2NzQ4MTc0LCJpc3MiOiJodHRwczovL29wZW5pZC1wcm92aWRlcjIuZXhhbXBsZS5jb20vYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiaHR0cHM6Ly9vcGVuaWQtcHJvdmlkZXIyLmV4YW1wbGUuY29tL2F1dGgvcmVhbG1zL21hc3RlciIsInR5cCI6IkluaXRpYWxBY2Nlc3NUb2tlbiJ9.3_57cFYMHl4uEw5mSocIaconUuwKmEn5n4VLRsJyIXI
    iam:
        human_readable_name: IAM Test Instance
        configuration_url: https://iam-test.indigo-datacloud.eu/
        registration_url: https://iam-test.indigo-datacloud.eu/register/5ae48a9d-2bc0-4d0d-a5af-55ea18a2c11f
        registration_token: eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiI1YWU0OGE5ZC0yYmMwLTRkMGQtYTVhZi01NWVhMThhMmMxMWYiLCJpc3MiOiJodHRwczpcL1wvaWFtLXRlc3QuaW5kaWdvLWRhdGFjbG91ZC5ldVwvIiwiaWF0IjoxNTc4NTY0MDk1LCJqdGkiOiI4OWJhM2EzMi01NGQwLTRhZjItOTBkMy0xYzMyYWFiMGJiY2IifQ.lY3wOwuycdZDSZn8Niqb6egJ4dgp_E8FFhebXOm1QXb467m3NghF7DgNvaQov-d_QNhw8RgWSBYbijL9GBSiboL5BJeEOrQ3by19bQHZZ58Ct1FF6Mi-To3IaAGl3XOFUNxeEk8zL4C8OdkYDf98P1pmHnkRFmeJfF5LjgE_fXc


proxy:
    keyfile: /etc/ssl/private/key.pem
    certfile: /etc/ssl/private/cert.crt
    domainname: python-proxy.example.com
    redirect:
        - /secure/redirect_uris
        - /secure/keycloak
        - /redirect
    contacts:
        - info@konstantinzangerle.de
    tls_port: 443
    plain_port: 80
    https_only: True

services:
    pap:
        origin_URL: pap
        proxy_URL: /pap
        AC: 'com.example.policysets.alwaysGrant'
    userinfo:
        origin_URL: userinfo
        proxy_URL: /userinfo
        AC: 'com.example.policysets.alwaysGrant'
    serviceA:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceA
        AC: com.example.policysets.loggedIn
        objectsetters:
            jsonsetter:
                enable: true
                url: http://json-server.example.com/posts/5/
                priority: 32
        obligations:
            obl_log:
                handlers:
                    obligation_file:
                        filename: "/var/log/oidcproxy/obl_test.log"

    serviceB:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceB
        AC: com.example.policysets.alwaysDeny
        objectsetters:
            json:
                enable: true
                url: http://json-server.example.com/
                priority: 32
    serviceC:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceC
        AC: com.example.policysets.inTestGroup
    serviceD:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceD
        AC: com.example.policysets.default
    serviceE:
        origin_URL: http://json-server.example.com
        proxy_URL: /serviceE
        AC: com.example.policysets.loggedIn
    serviceF:
        origin_URL: https://fortknox.example.com/bearer
        proxy_URL: /serviceF
        AC: com.example.policysets.loggedIn
        authentication:
            type: Bearer
            token: 1234
    serviceG:
        origin_URL: https://fortknox.example.com/cert
        proxy_URL: /serviceG
        AC: com.example.policysets.loggedIn
        authentication:
            type: Certificate
            keyfile: /etc/oidc-proxy/key.pem
            certfile: /etc/oidc-proxy/client.crt

access_control:
    json_dir:
        - /etc/oidc-proxy/acl

misc:
    log_level: DEBUG
    access_log: /var/log/oidcproxy/access.log
    error_log: /var/log/oidcproxy/error.log
    daemonize: True
    pid_file: /var/run/oidcproxy.pid

