#Test
openid_providers:
    default:
        configuration_url: https://openid-provider.example.com/auth/realms/master/
        configuration_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmYTM2N2E0MS0yNDRjLTQwNGUtYjU3NS05MDhhNDM2ZTc2YTMifQ.eyJqdGkiOiIwNDNmNjUyNC1hZjRkLTQ0MmYtYTM1ZS03YTJmZGM2YzQ2ZTAiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTc2NDg5NDU4LCJpc3MiOiJodHRwczovL29wZW5pZC1wcm92aWRlci5leGFtcGxlLmNvbS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJodHRwczovL29wZW5pZC1wcm92aWRlci5leGFtcGxlLmNvbS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJ0eXAiOiJJbml0aWFsQWNjZXNzVG9rZW4ifQ.CEQEU4vqbIxNwuKbn1VvOZdTI7qFmDTE3BEU59lZA3g
    second:
        configuration_url: https://openid-provider2.example.com/auth/realms/master/
        configuration_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5MDEzZDRkNS1jYTEwLTQyODItYmRjMy1jNWU5ZGQ3NDI4MWIifQ.eyJqdGkiOiIxZWM2NDA3ZC1jMzQ0LTRhOTAtODg2ZS01YjhmYjE4YjA0YmUiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTc2NDg5NTE5LCJpc3MiOiJodHRwczovL29wZW5pZC1wcm92aWRlcjIuZXhhbXBsZS5jb20vYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiaHR0cHM6Ly9vcGVuaWQtcHJvdmlkZXIyLmV4YW1wbGUuY29tL2F1dGgvcmVhbG1zL21hc3RlciIsInR5cCI6IkluaXRpYWxBY2Nlc3NUb2tlbiJ9.Fqg0NJGijgNVGrRAz8ppMahPbBZh5vdEr_rmtfMKkP8


proxy:
    keyfile: /etc/ssl/private/python-proxy.example.com.key
    certfile: /etc/ssl/private/python-proxy.example.com.crt
    hostname: https://python-proxy.example.com/
    redirect: /secure/redirect_uris
    redirect_uris:
        - https://python-proxy.example.com/secure/redirect_uris
    contacts:
        - info@konstantinzangerle.de

services:
    serviceA:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceA
        AC: com.example.policysets.loggedIn
    serviceB:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceB
        AC: com.example.policysets.alwaysDeny
    serviceC:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceC
        AC: com.example.policysets.inTestGroup

access_control:
    json_dir:
       - /etc/oidc-proxy/acl
