#Test
openid_providers:
    default:
        configuration_url: https://openid-provider.example.com/auth/realms/master/
        configuration_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1ZGYxY2VkMi1jMWY2LTQ5ZmQtYWUxYy00ZDU0MmQ0MWZmNzgifQ.eyJqdGkiOiJiYTA3NjVlZi1jZjQ0LTQ3ZWQtYmRkMC00YzYzMGZiZjljNmEiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTc2NzQ4MDY0LCJpc3MiOiJodHRwczovL29wZW5pZC1wcm92aWRlci5leGFtcGxlLmNvbS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJodHRwczovL29wZW5pZC1wcm92aWRlci5leGFtcGxlLmNvbS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJ0eXAiOiJJbml0aWFsQWNjZXNzVG9rZW4ifQ.ZI4DoZF7KCBmLsqKk49C3AqULkUrd2Chf2DEihuLTfE
    second:
        configuration_url: https://openid-provider2.example.com/auth/realms/master/
        configuration_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlZDBjNWY2MS0wNjM5LTRiMDQtOTVjZS1hMzhjNGJlMzczZWIifQ.eyJqdGkiOiI1OWYyZGY4My1mYjQ4LTRiZGYtYTc3NC02ODI5NTJjZDEwYTkiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTc2NzQ4MTc0LCJpc3MiOiJodHRwczovL29wZW5pZC1wcm92aWRlcjIuZXhhbXBsZS5jb20vYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiaHR0cHM6Ly9vcGVuaWQtcHJvdmlkZXIyLmV4YW1wbGUuY29tL2F1dGgvcmVhbG1zL21hc3RlciIsInR5cCI6IkluaXRpYWxBY2Nlc3NUb2tlbiJ9.3_57cFYMHl4uEw5mSocIaconUuwKmEn5n4VLRsJyIXI


proxy:
    keyfile: /etc/ssl/private/key.pem
    certfile: /etc/ssl/private/cert.crt
    hostname: https://python-proxy.example.com/
    redirect: /secure/redirect_uris
    redirect_uris:
        - https://python-proxy.example.com/secure/redirect_uris
    contacts:
        - info@konstantinzangerle.de

services:
    serviceA:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceA
        AC: com.example.policysets.loggedIn
    serviceB:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceB
        AC: com.example.policysets.alwaysDeny
    serviceC:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceC
        AC: com.example.policysets.inTestGroup
    serviceD:
        origin_URL: http://service-a.example.com
        proxy_URL: /serviceD
        AC: com.example.policysets.default
    serviceE:
        origin_URL: http://json-server.example.com
        proxy_URL: /serviceE
        AC: com.example.policysets.loggedIn

access_control:
    json_dir:
       - /etc/oidc-proxy/acl
